# Generated by Django 5.0 on 2024-01-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comments_bid_watchlist_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cats',
            new_name='Cat',
        ),
    ]
