# Generated by Django 5.0 on 2024-01-04 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_userid_listing_user_id_comment_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist_item',
            name='watcher_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
