# Generated by Django 5.0 on 2024-01-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabisote', '0005_rename_category_quiz_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Tag',
        ),
    ]
