# Generated by Django 5.0 on 2024-01-28 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabisote', '0006_rename_cat_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_item',
            name='answer',
        ),
        migrations.CreateModel(
            name='Answer_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kabisote.quiz_item')),
            ],
            options={
                'order_with_respect_to': 'question',
            },
        ),
    ]
