# Generated by Django 5.0 on 2024-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabisote', '0007_remove_quiz_item_answer_answer_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_item',
            name='answer_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterOrderWithRespectTo(
            name='answer_item',
            order_with_respect_to=None,
        ),
        migrations.AlterUniqueTogether(
            name='answer_item',
            unique_together={('question', 'answer_weight')},
        ),
    ]
