# Generated by Django 5.0 on 2024-02-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabisote', '0008_answer_item_answer_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='kabisote.tag'),
        ),
    ]
