# Generated by Django 5.0 on 2024-02-12 23:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabisote', '0011_alter_quiz_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
