# Generated by Django 5.0 on 2024-02-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabisote', '0012_alter_quiz_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz_item',
            options={'ordering': ['question_number']},
        ),
        migrations.AlterField(
            model_name='quiz_item',
            name='question_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='quiz_item',
            unique_together={('quiz', 'question_number')},
        ),
    ]
