# Generated by Django 5.0 on 2024-02-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabisote', '0014_alter_quiz_item_question_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer_item',
            old_name='answer',
            new_name='possible_answer',
        ),
    ]
