# Generated by Django 5.0 on 2024-01-04 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(blank=True, to='auctions.cat'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('c', 'closed'), ('o', 'open')], default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
