# Generated by Django 5.0 on 2024-01-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bid_bid_date_alter_comment_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-bid_price']},
        ),
    ]
